creation_rules:
  - path_regex: 'authority\.yaml'
    age: >-
      age1yubikey1q00kj0ycx49qwmup2xgxyt9z3n4xtr9qp25nhz434kexc6zcj7s5xt475yn,
      age1ns06lm4k6sdca2zhjggl5uhu3mzmvc4nunu2mrundw098uav5yzsgg0y98

  - path_regex: 'nas2\.yaml'
    age: >-
      age1yubikey1q00kj0ycx49qwmup2xgxyt9z3n4xtr9qp25nhz434kexc6zcj7s5xt475yn,
      age1ryn45582hdc40d4yv525h2ef5876qwucm87kjh8kl2h0lt2d8g7scect37

  - age: >-
      age1yubikey1q00kj0ycx49qwmup2xgxyt9z3n4xtr9qp25nhz434kexc6zcj7s5xt475yn
